In [1]:
import os
import mne
import datetime
import pandas as pd
import numpy as np
from tqdm.notebook import tqdm

In [2]:
path_subjects_hypno = 'D:\\samsung_original\\Samsung_3rd_PE\\scoring'
# path_subjects_hypno = 'G:\\다른 컴퓨터\\내 노트북\\USC\\Sleep dataset\\Samsung_2nd\\VD_sleep_scoring'

subjects_hypno = os.listdir(path_subjects_hypno)
subjects_hypno.sort()
print(subjects_hypno)
print(f'\n-- {len(subjects_hypno)} available hypno_labels as txt file\n')

total_hypno_start = []
total_hypno_end = []
total_index = []

for subject in subjects_hypno:
    path_temp_hypno = os.path.join(path_subjects_hypno, subject)
    with open(path_temp_hypno, 'r') as f:
        hypno_lines = f.readlines()
    hypno_start = hypno_lines[18].strip().split()[1]
    hypno_end = hypno_lines[-1].strip().split()[1]

    print(f'[hypno] {subject[0:5]} {hypno_start} ~ {hypno_end}')

    total_hypno_start.append(hypno_start)
    total_hypno_end.append(hypno_end)
    total_index.append(subject[0:8])    

dic_total = {
    'hypno_start': total_hypno_start,
    'hypno_end': total_hypno_end,
    'edf_start': np.zeros(len(subjects_hypno)),
    'edf_duration': np.zeros(len(subjects_hypno)),
    'edf_end': np.zeros(len(subjects_hypno)),
    'start_mismatch': np.zeros(len(subjects_hypno)),
    'end_mismatch': np.zeros(len(subjects_hypno))
}

df_total = pd.DataFrame(dic_total, index = total_index)
df_total

['PE150386 PE150386-Events.txt', 'PE180205 PE180205-Events.txt', 'PE180682 PE180682-Events.txt', 'PE180955 PE180955-Events.txt', 'PE181067 PE181067-Events.txt', 'PE190065 PE190065-Events.txt', 'PE190090 PE190090-Events.txt', 'PE190925 PE190925-Events.txt']

-- 8 available hypno_labels as txt file

[hypno] PE150 23:20:30 ~ 05:32:30
[hypno] PE180 23:15:00 ~ 06:53:30
[hypno] PE180 22:55:30 ~ 05:52:00
[hypno] PE180 23:30:00 ~ 06:07:00
[hypno] PE181 23:01:00 ~ 05:38:00
[hypno] PE190 00:17:30 ~ 09:08:30
[hypno] PE190 22:49:00 ~ 07:05:00
[hypno] PE190 21:23:00 ~ 06:04:30

,hypno_start,hypno_end,edf_start,edf_duration,edf_end,start_mismatch,end_mismatch
PE150386,23:20:30,05:32:30,0.0,0.0,0.0,0.0,0.0
PE180205,23:15:00,06:53:30,0.0,0.0,0.0,0.0,0.0
PE180682,22:55:30,05:52:00,0.0,0.0,0.0,0.0,0.0
PE180955,23:30:00,06:07:00,0.0,0.0,0.0,0.0,0.0
PE181067,23:01:00,05:38:00,0.0,0.0,0.0,0.0,0.0
PE190065,00:17:30,09:08:30,0.0,0.0,0.0,0.0,0.0
PE190090,22:49:00,07:05:00,0.0,0.0,0.0,0.0,0.0
PE190925,21:23:00,06:04:30,0.0,0.0,0.0,0.0,0.0

In [3]:
path_subjects_edf = 'D:\\samsung_original\\Samsung_3rd_PE\\edf'
# path_subjects_edf = 'G:\\다른 컴퓨터\\내 노트북\\USC\\Sleep dataset\\Samsung_2nd\\VD_edf'

subjects_edf = os.listdir(path_subjects_edf)
subjects_edf.sort()
print(subjects_edf)
print(f'\n-- {len(subjects_edf)} available edf files as edf file\n')

total_edf_start = []
total_edf_duration = []

i = 0
for i in tqdm(range(len(subjects_edf)), desc='EDF load and get meas info ... '):
    path_temp_edf = os.path.join(path_subjects_edf, subjects_edf[i], 'Traces.edf')
    raw = mne.io.read_raw_edf(path_temp_edf, preload=True, verbose=False)
    
    edf_start = str(raw.info['meas_date'])[11:19]
    edf_duration = str(datetime.timedelta(seconds=len(raw.times)/raw.info['sfreq']))
    
    #     print("subject   edf_start    edf_duration")
    
    print(f"{subjects_edf[i]}     {edf_start}     {edf_duration} ")
    total_edf_start.append(edf_start)
    total_edf_duration.append(edf_duration)

    df_total.loc[total_index[i], 'edf_start'] = edf_start
    df_total.loc[total_index[i], 'edf_duration'] = edf_duration

['PE150386_edf', 'PE180205_edf', 'PE180682_edf', 'PE180955_edf', 'PE181067_edf', 'PE190065_edf', 'PE190090_edf', 'PE190925_edf']

-- 8 available edf files as edf file

EDF load and get meas info ... :   0%|          | 0/8 [00:00<?, ?it/s]

[]
PE150386_edf     23:17:07     6:16:35
[]
PE180205_edf     23:13:15     7:40:50
[]
PE180682_edf     22:54:42     6:57:54
[]
PE180955_edf     23:29:08     6:38:00
[]
PE181067_edf     22:58:04     6:40:30
[]
PE190065_edf     00:15:24     8:53:40
[]
PE190090_edf     23:21:02     7:44:10
[]
PE190925_edf     21:20:22     8:45:06

In [6]:
df_total.to_csv('meas_time_info.csv')
df_total

,hypno_start,hypno_end,edf_start,edf_duration,edf_end,start_mismatch,end_mismatch
PE150386,23:20:30,05:32:30,23:17:07,6:16:35,0.0,0.0,0.0
PE180205,23:15:00,06:53:30,23:13:15,7:40:50,0.0,0.0,0.0
PE180682,22:55:30,05:52:00,22:54:42,6:57:54,0.0,0.0,0.0
PE180955,23:30:00,06:07:00,23:29:08,6:38:00,0.0,0.0,0.0
PE181067,23:01:00,05:38:00,22:58:04,6:40:30,0.0,0.0,0.0
PE190065,00:17:30,09:08:30,00:15:24,8:53:40,0.0,0.0,0.0
PE190090,22:49:00,07:05:00,23:21:02,7:44:10,0.0,0.0,0.0
PE190925,21:23:00,06:04:30,21:20:22,8:45:06,0.0,0.0,0.0